--REGLAS TABLA CINTURONES;
ALTER TABLE CINTURONES ADD CONSTRAINT PK_CINTURON PRIMARY KEY ( codigo_cin ) ;
ALTER TABLE CINTURONES ADD CONSTRAINT NN_DESCRIPCION_CIN CHECK ( descripcion_cin is not null ) ;

--REGLAS TABLA DEPORTISTAS;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT PK_DEPORTISTAS PRIMARY KEY ( nro_identificacion_dep ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_NOMBRE_DEP CHECK ( datos_dep.nombres is not null) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_PRIMER_APELLIDO_DEP CHECK ( datos_dep.primer_apellido is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_FECHA_NACIMIENTO_DEP CHECK ( datos_dep.fecha_nacimiento is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_PROGRAMA_ACADEMICO_DEP CHECK ( programa_academico_dep is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_SEMESTRE_DEP CHECK ( semestre_dep > 0 ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_MEDALLAS_DEP CHECK ( medallas_dep is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_DIRECCION_DEP CHECK ( datos_dep.direccion is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_GRUPO_DEP CHECK ( grupo_dep is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_CINTURON_ACTUAL_DEP CHECK ( cinturon_actual_dep is not null ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT NN_CINTURON_PROXIMO_DEP CHECK ( cinturon_proximo_dep is not null ) ;

--REGLAS TABLA ENTRENADOR;
ALTER TABLE ENTRENADORES ADD CONSTRAINT PK_ENTRENADOR PRIMARY KEY ( nro_identificacion_ent ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_NOMBRE_ENT CHECK ( datos_ent.nombres is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_PRIMER_APELLIDO_ENT CHECK ( datos_ent.primer_apellido is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_FECHA_NACIMIENTO_ENT CHECK ( datos_ent.fecha_nacimiento is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_TITULO_ENT CHECK ( titulo_ent is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_CINTURON_ENT CHECK ( cinturon_ent is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_ANIOS_EXPERIENCIA_ENT CHECK ( anios_experiencia_ent is not null ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT NN_DIRECCION_ENT CHECK ( datos_ent.direccion is not null ) ;

--REGLAS TABLA GRUPO;
ALTER TABLE GRUPOS ADD CONSTRAINT PK_GRUPO PRIMARY KEY ( codigo_gru ) ;
ALTER TABLE GRUPOS ADD CONSTRAINT NN_DESCRIPCION_GRU CHECK ( descripcion_gru is not null ) ;
ALTER TABLE GRUPOS ADD CONSTRAINT NN_ID_ENTRENADOR_GRU CHECK ( id_entrenador_gru is not null );

--REGLAS TABLA HISTORIA_DEPORTISTA;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT PK_HISTORIA_DEPORTISTA PRIMARY KEY ( nro_historia_his ) ;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT NN_ID_DEPORTISTA_HIS CHECK ( id_deportista_his is not null ) ;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT NN_COD_CINTURON_HIS CHECK ( cod_cinturon_his is not null ) ;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT NN_FECHA_HIS CHECK ( fecha_his is not null ) ;

-- REGLAS FORANEAS;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT FK_GRUPO_DEP FOREIGN KEY ( grupo_dep ) REFERENCES GRUPOS ( codigo_gru ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT FK_CINTURON_DEP FOREIGN KEY ( cinturon_actual_dep ) REFERENCES CINTURONES ( codigo_cin ) ;
ALTER TABLE DEPORTISTAS ADD CONSTRAINT FK_CINTURON_DEP_v2 FOREIGN KEY ( cinturon_proximo_dep ) REFERENCES CINTURONES ( codigo_cin ) ;
ALTER TABLE ENTRENADORES ADD CONSTRAINT FK_CINTURON_ENT FOREIGN KEY ( cinturon_ent ) REFERENCES CINTURONES ( codigo_cin ) ;
ALTER TABLE GRUPOS ADD CONSTRAINT FK_ENTRENADOR_GRU FOREIGN KEY ( id_entrenador_gru ) REFERENCES ENTRENADORES ( nro_identificacion_ent ) ;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT FK_CINTURON_HIS FOREIGN KEY ( cod_cinturon_his ) REFERENCES CINTURONES ( codigo_cin ) ;
ALTER TABLE HISTORIA_DEPORTISTAS ADD CONSTRAINT FK_DEPORTISTA_HIS FOREIGN KEY ( id_deportista_his ) REFERENCES DEPORTISTAS ( nro_identificacion_dep );